http://localhost:8000/posts
Content-Type: application/json

{
"user_id": "03347067-a190-4984-86c2-33b920a2ae65",
"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNGQ1MzU4MDQtNzg1ZS00NDhiLWI0YzktZWU4ZjM2MmNlY2EzIiwiZm5hbWUiOm51bGwsImxuYW1lIjpudWxsLCJ1c2VybmFtZSI6ImV2ZSIsImVtYWlsIjoiZXZlQG1pZG5pZ2h0d3JpdGUuY29tIiwicGFzc3dvcmQiOiIkMmEkMTAkNWxYdUEzVG1YcThYUmpSb2JzV2JJT0M5YUI3YlFnUnpVaFgxOEhZWWQ2bTNWbkZNQ2tuTUMiLCJpYXQiOjE2NjQxOTM1NDIsImV4cCI6MTY2NDE5NzE0Mn0.F1NLDrPhINbxDnpjU5Xme3cZg3Fa1-nh53AqPf5Gc_k"
}